// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pingGrpc.proto

package uPinger

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IcmpResult_ResultType int32

const (
	IcmpResult_IcmpResultTypeUnknown             IcmpResult_ResultType = 0
	IcmpResult_IcmpResultTypeReceive             IcmpResult_ResultType = 1
	IcmpResult_IcmpResultTypeReceiveAfterTimeout IcmpResult_ResultType = 2
	IcmpResult_IcmpResultTypeTTLExceeded         IcmpResult_ResultType = 3
	IcmpResult_IcmpResultTypeTimeout             IcmpResult_ResultType = 4
)

var IcmpResult_ResultType_name = map[int32]string{
	0: "IcmpResultTypeUnknown",
	1: "IcmpResultTypeReceive",
	2: "IcmpResultTypeReceiveAfterTimeout",
	3: "IcmpResultTypeTTLExceeded",
	4: "IcmpResultTypeTimeout",
}

var IcmpResult_ResultType_value = map[string]int32{
	"IcmpResultTypeUnknown":             0,
	"IcmpResultTypeReceive":             1,
	"IcmpResultTypeReceiveAfterTimeout": 2,
	"IcmpResultTypeTTLExceeded":         3,
	"IcmpResultTypeTimeout":             4,
}

func (x IcmpResult_ResultType) String() string {
	return proto.EnumName(IcmpResult_ResultType_name, int32(x))
}

func (IcmpResult_ResultType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{6, 0}
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{0}
}

func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (m *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(m, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type StartRequest struct {
	Description           string                     `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	Targets               []*StartRequest_IcmpTarget `protobuf:"bytes,2,rep,name=Targets,proto3" json:"Targets,omitempty"`
	IntervalMillisec      uint64                     `protobuf:"varint,3,opt,name=IntervalMillisec,proto3" json:"IntervalMillisec,omitempty"`
	TimeoutMillisec       uint64                     `protobuf:"varint,4,opt,name=TimeoutMillisec,proto3" json:"TimeoutMillisec,omitempty"`
	StatisticsCountsNum   uint64                     `protobuf:"varint,5,opt,name=StatisticsCountsNum,proto3" json:"StatisticsCountsNum,omitempty"`
	StopPingerSec         uint64                     `protobuf:"varint,6,opt,name=StopPingerSec,proto3" json:"StopPingerSec,omitempty"`
	StatisticsIntervalSec uint64                     `protobuf:"varint,7,opt,name=StatisticsIntervalSec,proto3" json:"StatisticsIntervalSec,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                   `json:"-"`
	XXX_unrecognized      []byte                     `json:"-"`
	XXX_sizecache         int32                      `json:"-"`
}

func (m *StartRequest) Reset()         { *m = StartRequest{} }
func (m *StartRequest) String() string { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()    {}
func (*StartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{1}
}

func (m *StartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest.Unmarshal(m, b)
}
func (m *StartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest.Marshal(b, m, deterministic)
}
func (m *StartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest.Merge(m, src)
}
func (m *StartRequest) XXX_Size() int {
	return xxx_messageInfo_StartRequest.Size(m)
}
func (m *StartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest proto.InternalMessageInfo

func (m *StartRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StartRequest) GetTargets() []*StartRequest_IcmpTarget {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *StartRequest) GetIntervalMillisec() uint64 {
	if m != nil {
		return m.IntervalMillisec
	}
	return 0
}

func (m *StartRequest) GetTimeoutMillisec() uint64 {
	if m != nil {
		return m.TimeoutMillisec
	}
	return 0
}

func (m *StartRequest) GetStatisticsCountsNum() uint64 {
	if m != nil {
		return m.StatisticsCountsNum
	}
	return 0
}

func (m *StartRequest) GetStopPingerSec() uint64 {
	if m != nil {
		return m.StopPingerSec
	}
	return 0
}

func (m *StartRequest) GetStatisticsIntervalSec() uint64 {
	if m != nil {
		return m.StatisticsIntervalSec
	}
	return 0
}

type StartRequest_IcmpTarget struct {
	TargetIP             string   `protobuf:"bytes,1,opt,name=TargetIP,proto3" json:"TargetIP,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartRequest_IcmpTarget) Reset()         { *m = StartRequest_IcmpTarget{} }
func (m *StartRequest_IcmpTarget) String() string { return proto.CompactTextString(m) }
func (*StartRequest_IcmpTarget) ProtoMessage()    {}
func (*StartRequest_IcmpTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{1, 0}
}

func (m *StartRequest_IcmpTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartRequest_IcmpTarget.Unmarshal(m, b)
}
func (m *StartRequest_IcmpTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartRequest_IcmpTarget.Marshal(b, m, deterministic)
}
func (m *StartRequest_IcmpTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartRequest_IcmpTarget.Merge(m, src)
}
func (m *StartRequest_IcmpTarget) XXX_Size() int {
	return xxx_messageInfo_StartRequest_IcmpTarget.Size(m)
}
func (m *StartRequest_IcmpTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_StartRequest_IcmpTarget.DiscardUnknown(m)
}

var xxx_messageInfo_StartRequest_IcmpTarget proto.InternalMessageInfo

func (m *StartRequest_IcmpTarget) GetTargetIP() string {
	if m != nil {
		return m.TargetIP
	}
	return ""
}

func (m *StartRequest_IcmpTarget) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type Statistics struct {
	Targets              []*Statistics_SuccessCount `protobuf:"bytes,1,rep,name=Targets,proto3" json:"Targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{2}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetTargets() []*Statistics_SuccessCount {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Statistics_SuccessCount struct {
	TargetID             uint32   `protobuf:"fixed32,1,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statistics_SuccessCount) Reset()         { *m = Statistics_SuccessCount{} }
func (m *Statistics_SuccessCount) String() string { return proto.CompactTextString(m) }
func (*Statistics_SuccessCount) ProtoMessage()    {}
func (*Statistics_SuccessCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{2, 0}
}

func (m *Statistics_SuccessCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics_SuccessCount.Unmarshal(m, b)
}
func (m *Statistics_SuccessCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics_SuccessCount.Marshal(b, m, deterministic)
}
func (m *Statistics_SuccessCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics_SuccessCount.Merge(m, src)
}
func (m *Statistics_SuccessCount) XXX_Size() int {
	return xxx_messageInfo_Statistics_SuccessCount.Size(m)
}
func (m *Statistics_SuccessCount) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics_SuccessCount.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics_SuccessCount proto.InternalMessageInfo

func (m *Statistics_SuccessCount) GetTargetID() uint32 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *Statistics_SuccessCount) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type PingerID struct {
	PingerID             uint32   `protobuf:"varint,1,opt,name=PingerID,proto3" json:"PingerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingerID) Reset()         { *m = PingerID{} }
func (m *PingerID) String() string { return proto.CompactTextString(m) }
func (*PingerID) ProtoMessage()    {}
func (*PingerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{3}
}

func (m *PingerID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingerID.Unmarshal(m, b)
}
func (m *PingerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingerID.Marshal(b, m, deterministic)
}
func (m *PingerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingerID.Merge(m, src)
}
func (m *PingerID) XXX_Size() int {
	return xxx_messageInfo_PingerID.Size(m)
}
func (m *PingerID) XXX_DiscardUnknown() {
	xxx_messageInfo_PingerID.DiscardUnknown(m)
}

var xxx_messageInfo_PingerID proto.InternalMessageInfo

func (m *PingerID) GetPingerID() uint32 {
	if m != nil {
		return m.PingerID
	}
	return 0
}

type PingerList struct {
	Pingers              []*PingerList_PingerSumally `protobuf:"bytes,1,rep,name=Pingers,proto3" json:"Pingers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *PingerList) Reset()         { *m = PingerList{} }
func (m *PingerList) String() string { return proto.CompactTextString(m) }
func (*PingerList) ProtoMessage()    {}
func (*PingerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{4}
}

func (m *PingerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingerList.Unmarshal(m, b)
}
func (m *PingerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingerList.Marshal(b, m, deterministic)
}
func (m *PingerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingerList.Merge(m, src)
}
func (m *PingerList) XXX_Size() int {
	return xxx_messageInfo_PingerList.Size(m)
}
func (m *PingerList) XXX_DiscardUnknown() {
	xxx_messageInfo_PingerList.DiscardUnknown(m)
}

var xxx_messageInfo_PingerList proto.InternalMessageInfo

func (m *PingerList) GetPingers() []*PingerList_PingerSumally {
	if m != nil {
		return m.Pingers
	}
	return nil
}

type PingerList_PingerSumally struct {
	PingerID             uint32   `protobuf:"varint,1,opt,name=PingerID,proto3" json:"PingerID,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	StartUnixNanosec     uint64   `protobuf:"varint,3,opt,name=StartUnixNanosec,proto3" json:"StartUnixNanosec,omitempty"`
	ExpireUnixNanosec    uint64   `protobuf:"varint,4,opt,name=ExpireUnixNanosec,proto3" json:"ExpireUnixNanosec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingerList_PingerSumally) Reset()         { *m = PingerList_PingerSumally{} }
func (m *PingerList_PingerSumally) String() string { return proto.CompactTextString(m) }
func (*PingerList_PingerSumally) ProtoMessage()    {}
func (*PingerList_PingerSumally) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{4, 0}
}

func (m *PingerList_PingerSumally) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingerList_PingerSumally.Unmarshal(m, b)
}
func (m *PingerList_PingerSumally) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingerList_PingerSumally.Marshal(b, m, deterministic)
}
func (m *PingerList_PingerSumally) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingerList_PingerSumally.Merge(m, src)
}
func (m *PingerList_PingerSumally) XXX_Size() int {
	return xxx_messageInfo_PingerList_PingerSumally.Size(m)
}
func (m *PingerList_PingerSumally) XXX_DiscardUnknown() {
	xxx_messageInfo_PingerList_PingerSumally.DiscardUnknown(m)
}

var xxx_messageInfo_PingerList_PingerSumally proto.InternalMessageInfo

func (m *PingerList_PingerSumally) GetPingerID() uint32 {
	if m != nil {
		return m.PingerID
	}
	return 0
}

func (m *PingerList_PingerSumally) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PingerList_PingerSumally) GetStartUnixNanosec() uint64 {
	if m != nil {
		return m.StartUnixNanosec
	}
	return 0
}

func (m *PingerList_PingerSumally) GetExpireUnixNanosec() uint64 {
	if m != nil {
		return m.ExpireUnixNanosec
	}
	return 0
}

type PingerInfo struct {
	Description           string                   `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	Targets               []*PingerInfo_IcmpTarget `protobuf:"bytes,2,rep,name=Targets,proto3" json:"Targets,omitempty"`
	IntervalMillisec      uint64                   `protobuf:"varint,3,opt,name=IntervalMillisec,proto3" json:"IntervalMillisec,omitempty"`
	TimeoutMillisec       uint64                   `protobuf:"varint,4,opt,name=TimeoutMillisec,proto3" json:"TimeoutMillisec,omitempty"`
	StatisticsCountsNum   uint64                   `protobuf:"varint,5,opt,name=StatisticsCountsNum,proto3" json:"StatisticsCountsNum,omitempty"`
	StatisticsIntervalSec uint64                   `protobuf:"varint,6,opt,name=StatisticsIntervalSec,proto3" json:"StatisticsIntervalSec,omitempty"`
	StartUnixNanosec      uint64                   `protobuf:"varint,8,opt,name=StartUnixNanosec,proto3" json:"StartUnixNanosec,omitempty"`
	ExpireUnixNanosec     uint64                   `protobuf:"varint,7,opt,name=ExpireUnixNanosec,proto3" json:"ExpireUnixNanosec,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                 `json:"-"`
	XXX_unrecognized      []byte                   `json:"-"`
	XXX_sizecache         int32                    `json:"-"`
}

func (m *PingerInfo) Reset()         { *m = PingerInfo{} }
func (m *PingerInfo) String() string { return proto.CompactTextString(m) }
func (*PingerInfo) ProtoMessage()    {}
func (*PingerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{5}
}

func (m *PingerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingerInfo.Unmarshal(m, b)
}
func (m *PingerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingerInfo.Marshal(b, m, deterministic)
}
func (m *PingerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingerInfo.Merge(m, src)
}
func (m *PingerInfo) XXX_Size() int {
	return xxx_messageInfo_PingerInfo.Size(m)
}
func (m *PingerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PingerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PingerInfo proto.InternalMessageInfo

func (m *PingerInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *PingerInfo) GetTargets() []*PingerInfo_IcmpTarget {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *PingerInfo) GetIntervalMillisec() uint64 {
	if m != nil {
		return m.IntervalMillisec
	}
	return 0
}

func (m *PingerInfo) GetTimeoutMillisec() uint64 {
	if m != nil {
		return m.TimeoutMillisec
	}
	return 0
}

func (m *PingerInfo) GetStatisticsCountsNum() uint64 {
	if m != nil {
		return m.StatisticsCountsNum
	}
	return 0
}

func (m *PingerInfo) GetStatisticsIntervalSec() uint64 {
	if m != nil {
		return m.StatisticsIntervalSec
	}
	return 0
}

func (m *PingerInfo) GetStartUnixNanosec() uint64 {
	if m != nil {
		return m.StartUnixNanosec
	}
	return 0
}

func (m *PingerInfo) GetExpireUnixNanosec() uint64 {
	if m != nil {
		return m.ExpireUnixNanosec
	}
	return 0
}

type PingerInfo_IcmpTarget struct {
	TargetIP             string   `protobuf:"bytes,1,opt,name=TargetIP,proto3" json:"TargetIP,omitempty"`
	TargetBinIP          string   `protobuf:"bytes,4,opt,name=TargetBinIP,proto3" json:"TargetBinIP,omitempty"`
	Comment              string   `protobuf:"bytes,2,opt,name=Comment,proto3" json:"Comment,omitempty"`
	TargetID             uint32   `protobuf:"fixed32,3,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingerInfo_IcmpTarget) Reset()         { *m = PingerInfo_IcmpTarget{} }
func (m *PingerInfo_IcmpTarget) String() string { return proto.CompactTextString(m) }
func (*PingerInfo_IcmpTarget) ProtoMessage()    {}
func (*PingerInfo_IcmpTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{5, 0}
}

func (m *PingerInfo_IcmpTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingerInfo_IcmpTarget.Unmarshal(m, b)
}
func (m *PingerInfo_IcmpTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingerInfo_IcmpTarget.Marshal(b, m, deterministic)
}
func (m *PingerInfo_IcmpTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingerInfo_IcmpTarget.Merge(m, src)
}
func (m *PingerInfo_IcmpTarget) XXX_Size() int {
	return xxx_messageInfo_PingerInfo_IcmpTarget.Size(m)
}
func (m *PingerInfo_IcmpTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_PingerInfo_IcmpTarget.DiscardUnknown(m)
}

var xxx_messageInfo_PingerInfo_IcmpTarget proto.InternalMessageInfo

func (m *PingerInfo_IcmpTarget) GetTargetIP() string {
	if m != nil {
		return m.TargetIP
	}
	return ""
}

func (m *PingerInfo_IcmpTarget) GetTargetBinIP() string {
	if m != nil {
		return m.TargetBinIP
	}
	return ""
}

func (m *PingerInfo_IcmpTarget) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

func (m *PingerInfo_IcmpTarget) GetTargetID() uint32 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

type IcmpResult struct {
	Type                   IcmpResult_ResultType `protobuf:"varint,1,opt,name=type,proto3,enum=uPinger.IcmpResult_ResultType" json:"type,omitempty"`
	TargetID               uint32                `protobuf:"fixed32,2,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	BinPeerIP              uint32                `protobuf:"fixed32,3,opt,name=BinPeerIP,proto3" json:"BinPeerIP,omitempty"`
	Sequence               int64                 `protobuf:"varint,4,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	SendTimeUnixNanosec    int64                 `protobuf:"varint,5,opt,name=SendTimeUnixNanosec,proto3" json:"SendTimeUnixNanosec,omitempty"`
	ReceiveTimeUnixNanosec int64                 `protobuf:"varint,6,opt,name=ReceiveTimeUnixNanosec,proto3" json:"ReceiveTimeUnixNanosec,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}              `json:"-"`
	XXX_unrecognized       []byte                `json:"-"`
	XXX_sizecache          int32                 `json:"-"`
}

func (m *IcmpResult) Reset()         { *m = IcmpResult{} }
func (m *IcmpResult) String() string { return proto.CompactTextString(m) }
func (*IcmpResult) ProtoMessage()    {}
func (*IcmpResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b912ac693319c27c, []int{6}
}

func (m *IcmpResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IcmpResult.Unmarshal(m, b)
}
func (m *IcmpResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IcmpResult.Marshal(b, m, deterministic)
}
func (m *IcmpResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IcmpResult.Merge(m, src)
}
func (m *IcmpResult) XXX_Size() int {
	return xxx_messageInfo_IcmpResult.Size(m)
}
func (m *IcmpResult) XXX_DiscardUnknown() {
	xxx_messageInfo_IcmpResult.DiscardUnknown(m)
}

var xxx_messageInfo_IcmpResult proto.InternalMessageInfo

func (m *IcmpResult) GetType() IcmpResult_ResultType {
	if m != nil {
		return m.Type
	}
	return IcmpResult_IcmpResultTypeUnknown
}

func (m *IcmpResult) GetTargetID() uint32 {
	if m != nil {
		return m.TargetID
	}
	return 0
}

func (m *IcmpResult) GetBinPeerIP() uint32 {
	if m != nil {
		return m.BinPeerIP
	}
	return 0
}

func (m *IcmpResult) GetSequence() int64 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *IcmpResult) GetSendTimeUnixNanosec() int64 {
	if m != nil {
		return m.SendTimeUnixNanosec
	}
	return 0
}

func (m *IcmpResult) GetReceiveTimeUnixNanosec() int64 {
	if m != nil {
		return m.ReceiveTimeUnixNanosec
	}
	return 0
}

func init() {
	proto.RegisterEnum("uPinger.IcmpResult_ResultType", IcmpResult_ResultType_name, IcmpResult_ResultType_value)
	proto.RegisterType((*Null)(nil), "uPinger.Null")
	proto.RegisterType((*StartRequest)(nil), "uPinger.StartRequest")
	proto.RegisterType((*StartRequest_IcmpTarget)(nil), "uPinger.StartRequest.IcmpTarget")
	proto.RegisterType((*Statistics)(nil), "uPinger.Statistics")
	proto.RegisterType((*Statistics_SuccessCount)(nil), "uPinger.Statistics.SuccessCount")
	proto.RegisterType((*PingerID)(nil), "uPinger.PingerID")
	proto.RegisterType((*PingerList)(nil), "uPinger.PingerList")
	proto.RegisterType((*PingerList_PingerSumally)(nil), "uPinger.PingerList.PingerSumally")
	proto.RegisterType((*PingerInfo)(nil), "uPinger.PingerInfo")
	proto.RegisterType((*PingerInfo_IcmpTarget)(nil), "uPinger.PingerInfo.IcmpTarget")
	proto.RegisterType((*IcmpResult)(nil), "uPinger.IcmpResult")
}

func init() {
	proto.RegisterFile("pingGrpc.proto", fileDescriptor_b912ac693319c27c)
}

var fileDescriptor_b912ac693319c27c = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0x8e, 0xe3, 0x5c, 0xda, 0xd3, 0xa6, 0x7f, 0x3a, 0xfd, 0x8b, 0x52, 0x0b, 0x50, 0x6a, 0x01,
	0x8a, 0x2a, 0x14, 0x55, 0x2d, 0x20, 0x6e, 0x0b, 0x68, 0x53, 0x55, 0x91, 0x4a, 0x15, 0x39, 0xe9,
	0x03, 0x04, 0xf7, 0xb4, 0x1a, 0xe1, 0x8c, 0x8d, 0x3d, 0x2e, 0xed, 0x0e, 0x89, 0x1d, 0x6b, 0xde,
	0x00, 0x09, 0x1e, 0x89, 0x07, 0xe1, 0x05, 0x90, 0xc7, 0xb7, 0xf1, 0x25, 0x51, 0xd9, 0xb1, 0x8a,
	0xcf, 0x39, 0xdf, 0x37, 0xe7, 0x3e, 0x13, 0x58, 0x73, 0x28, 0xbb, 0x3c, 0x76, 0x1d, 0xb3, 0xef,
	0xb8, 0x36, 0xb7, 0x49, 0xd3, 0x1f, 0x51, 0x76, 0x89, 0xae, 0xde, 0x80, 0xda, 0xa9, 0x6f, 0x59,
	0xfa, 0x37, 0x15, 0x56, 0xc7, 0x7c, 0xea, 0x72, 0x03, 0x3f, 0xfa, 0xe8, 0x71, 0xd2, 0x85, 0x95,
	0x01, 0x7a, 0xa6, 0x4b, 0x1d, 0x4e, 0x6d, 0xd6, 0x51, 0xba, 0x4a, 0x6f, 0xd9, 0x90, 0x55, 0xe4,
	0x25, 0x34, 0x27, 0x53, 0xf7, 0x12, 0xb9, 0xd7, 0xa9, 0x76, 0xd5, 0xde, 0xca, 0x5e, 0xb7, 0x1f,
	0x9d, 0xda, 0x97, 0x4f, 0xea, 0x0f, 0xcd, 0x99, 0x13, 0x02, 0x8d, 0x98, 0x40, 0x76, 0xa0, 0x3d,
	0x64, 0x1c, 0xdd, 0xab, 0xa9, 0xf5, 0x8e, 0x5a, 0x16, 0xf5, 0xd0, 0xec, 0xa8, 0x5d, 0xa5, 0x57,
	0x33, 0x0a, 0x7a, 0xd2, 0x83, 0xff, 0x26, 0x74, 0x86, 0xb6, 0xcf, 0x13, 0x68, 0x4d, 0x40, 0xf3,
	0x6a, 0xb2, 0x0b, 0x1b, 0x63, 0x3e, 0xe5, 0xd4, 0xe3, 0xd4, 0xf4, 0x0e, 0x6d, 0x9f, 0x71, 0xef,
	0xd4, 0x9f, 0x75, 0xea, 0x02, 0x5d, 0x66, 0x22, 0x0f, 0xa0, 0x35, 0xe6, 0xb6, 0x13, 0x86, 0x3d,
	0x46, 0xb3, 0xd3, 0x10, 0xd8, 0xac, 0x92, 0x3c, 0x81, 0xcd, 0x94, 0x1c, 0xc7, 0x17, 0xa0, 0x9b,
	0x02, 0x5d, 0x6e, 0xd4, 0x0e, 0x00, 0xd2, 0xd4, 0x89, 0x06, 0x4b, 0xe1, 0xd7, 0x70, 0x14, 0x15,
	0x33, 0x91, 0x49, 0x07, 0x9a, 0x87, 0xf6, 0x6c, 0x86, 0x8c, 0x77, 0xaa, 0xc2, 0x14, 0x8b, 0xfa,
	0x57, 0x05, 0x20, 0x3d, 0x5d, 0x2e, 0xb9, 0x52, 0x2c, 0x79, 0x84, 0xea, 0x8f, 0x7d, 0xd3, 0x44,
	0x2f, 0xcc, 0x32, 0x29, 0xb9, 0xf6, 0x06, 0x56, 0x65, 0x83, 0x14, 0xd0, 0x40, 0x04, 0xd4, 0x4c,
	0x02, 0x1a, 0x90, 0xff, 0xa1, 0x2e, 0x40, 0x22, 0x1c, 0xd5, 0x08, 0x05, 0xfd, 0x11, 0x2c, 0x85,
	0xce, 0x86, 0x83, 0x80, 0x1d, 0x7f, 0x0b, 0x76, 0xcb, 0x48, 0x64, 0xfd, 0xb7, 0x02, 0x10, 0x0a,
	0x27, 0xd4, 0xe3, 0xe4, 0x15, 0x34, 0x43, 0x29, 0x0e, 0x7a, 0x3b, 0x09, 0x3a, 0x45, 0x45, 0x9f,
	0x63, 0x7f, 0x36, 0xb5, 0xac, 0x1b, 0x23, 0x66, 0x68, 0x3f, 0x15, 0x68, 0x65, 0x4c, 0x8b, 0x3c,
	0xe7, 0x87, 0xb6, 0x5a, 0x1c, 0xda, 0x1d, 0x68, 0x8b, 0xe1, 0x3c, 0x63, 0xf4, 0xfa, 0x74, 0xca,
	0x6c, 0x69, 0xf0, 0xf2, 0x7a, 0xf2, 0x18, 0xd6, 0x8f, 0xae, 0x1d, 0xea, 0xa2, 0x0c, 0x0e, 0x47,
	0xaf, 0x68, 0xd0, 0xbf, 0xd4, 0xe2, 0xac, 0x87, 0xec, 0xc2, 0xbe, 0xc5, 0xfe, 0x3c, 0xcf, 0xef,
	0xcf, 0xfd, 0x5c, 0x5d, 0x82, 0x73, 0xfe, 0xe9, 0xed, 0x99, 0xbb, 0x17, 0x8d, 0x05, 0x7b, 0x51,
	0xda, 0x82, 0xa5, 0xbf, 0x69, 0x41, 0x73, 0x4e, 0x0b, 0xb4, 0xcf, 0xca, 0xad, 0x57, 0xae, 0x0b,
	0x2b, 0xe1, 0xf7, 0x01, 0x65, 0xc3, 0x91, 0x28, 0xc9, 0xb2, 0x21, 0xab, 0xe6, 0x2f, 0x65, 0x66,
	0x73, 0xd4, 0xec, 0xe6, 0xe8, 0x3f, 0xd4, 0x30, 0x04, 0x03, 0x3d, 0xdf, 0xe2, 0x64, 0x0f, 0x6a,
	0xfc, 0xc6, 0x41, 0xe1, 0x7e, 0x4d, 0x6a, 0x70, 0x0a, 0xe9, 0x87, 0x3f, 0x93, 0x1b, 0x07, 0x0d,
	0x81, 0xcd, 0x1c, 0x5f, 0xcd, 0x2d, 0xe6, 0x5d, 0x58, 0x3e, 0xa0, 0x6c, 0x84, 0xe8, 0x0e, 0x47,
	0x91, 0xef, 0x54, 0x11, 0x30, 0xc7, 0xc1, 0xa5, 0xcb, 0x4c, 0x14, 0x19, 0xa9, 0x46, 0x22, 0x8b,
	0xee, 0x22, 0x3b, 0x0f, 0x9a, 0x2e, 0xd7, 0xb2, 0x2e, 0x60, 0x65, 0x26, 0xf2, 0x0c, 0xee, 0x18,
	0x68, 0x22, 0xbd, 0xc2, 0x3c, 0xa9, 0x21, 0x48, 0x73, 0xac, 0xfa, 0x77, 0x05, 0x20, 0x4d, 0x8a,
	0x6c, 0xc1, 0x66, 0x9a, 0x6d, 0xa0, 0x39, 0x63, 0x1f, 0x98, 0xfd, 0x89, 0xb5, 0x2b, 0x45, 0x53,
	0x74, 0x62, 0x5b, 0x21, 0x0f, 0x61, 0xbb, 0xd4, 0xf4, 0xf6, 0x82, 0xa3, 0x1b, 0x4d, 0x6e, 0xbb,
	0x4a, 0xee, 0xc1, 0x56, 0x16, 0x36, 0x99, 0x9c, 0x1c, 0x5d, 0x9b, 0x88, 0xe7, 0x78, 0xde, 0x56,
	0x8b, 0x0e, 0x62, 0x66, 0x6d, 0xef, 0x57, 0x15, 0x1a, 0x61, 0x33, 0xc8, 0x3e, 0xd4, 0xc5, 0xe0,
	0x91, 0xcd, 0xd2, 0x07, 0x4c, 0x5b, 0xcf, 0xef, 0xe5, 0x40, 0xaf, 0x90, 0x1d, 0xa8, 0x05, 0x8f,
	0x04, 0x29, 0x1a, 0xb5, 0x56, 0xa2, 0x12, 0x4f, 0x6b, 0x85, 0x3c, 0x85, 0xd6, 0x31, 0x72, 0xe9,
	0x4a, 0xcc, 0x22, 0xb4, 0x8d, 0x92, 0x0b, 0x51, 0xaf, 0x90, 0x17, 0x12, 0x4d, 0xdc, 0x29, 0x25,
	0xbe, 0x36, 0x4a, 0xee, 0x0c, 0xbd, 0x42, 0x5e, 0xc3, 0xda, 0x31, 0x72, 0x4f, 0x7a, 0x3a, 0x16,
	0x72, 0x53, 0x9c, 0x5e, 0xd9, 0x55, 0x62, 0xb6, 0x34, 0xc7, 0x0b, 0xd9, 0x29, 0x2e, 0x60, 0xbf,
	0x6f, 0x88, 0xbf, 0x18, 0xfb, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x5a, 0x75, 0x07, 0x74,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PingerClient is the client API for Pinger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingerClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*PingerID, error)
	Stop(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (*Null, error)
	GetPingerList(ctx context.Context, in *Null, opts ...grpc.CallOption) (*PingerList, error)
	GetPingerInfo(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (*PingerInfo, error)
	GetsStatistics(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (Pinger_GetsStatisticsClient, error)
	GetsIcmpResult(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (Pinger_GetsIcmpResultClient, error)
}

type pingerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingerClient(cc grpc.ClientConnInterface) PingerClient {
	return &pingerClient{cc}
}

func (c *pingerClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*PingerID, error) {
	out := new(PingerID)
	err := c.cc.Invoke(ctx, "/uPinger.Pinger/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) Stop(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (*Null, error) {
	out := new(Null)
	err := c.cc.Invoke(ctx, "/uPinger.Pinger/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) GetPingerList(ctx context.Context, in *Null, opts ...grpc.CallOption) (*PingerList, error) {
	out := new(PingerList)
	err := c.cc.Invoke(ctx, "/uPinger.Pinger/GetPingerList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) GetPingerInfo(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (*PingerInfo, error) {
	out := new(PingerInfo)
	err := c.cc.Invoke(ctx, "/uPinger.Pinger/GetPingerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pingerClient) GetsStatistics(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (Pinger_GetsStatisticsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Pinger_serviceDesc.Streams[0], "/uPinger.Pinger/GetsStatistics", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingerGetsStatisticsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Pinger_GetsStatisticsClient interface {
	Recv() (*Statistics, error)
	grpc.ClientStream
}

type pingerGetsStatisticsClient struct {
	grpc.ClientStream
}

func (x *pingerGetsStatisticsClient) Recv() (*Statistics, error) {
	m := new(Statistics)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pingerClient) GetsIcmpResult(ctx context.Context, in *PingerID, opts ...grpc.CallOption) (Pinger_GetsIcmpResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Pinger_serviceDesc.Streams[1], "/uPinger.Pinger/GetsIcmpResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &pingerGetsIcmpResultClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Pinger_GetsIcmpResultClient interface {
	Recv() (*IcmpResult, error)
	grpc.ClientStream
}

type pingerGetsIcmpResultClient struct {
	grpc.ClientStream
}

func (x *pingerGetsIcmpResultClient) Recv() (*IcmpResult, error) {
	m := new(IcmpResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PingerServer is the server API for Pinger service.
type PingerServer interface {
	Start(context.Context, *StartRequest) (*PingerID, error)
	Stop(context.Context, *PingerID) (*Null, error)
	GetPingerList(context.Context, *Null) (*PingerList, error)
	GetPingerInfo(context.Context, *PingerID) (*PingerInfo, error)
	GetsStatistics(*PingerID, Pinger_GetsStatisticsServer) error
	GetsIcmpResult(*PingerID, Pinger_GetsIcmpResultServer) error
}

// UnimplementedPingerServer can be embedded to have forward compatible implementations.
type UnimplementedPingerServer struct {
}

func (*UnimplementedPingerServer) Start(ctx context.Context, req *StartRequest) (*PingerID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedPingerServer) Stop(ctx context.Context, req *PingerID) (*Null, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedPingerServer) GetPingerList(ctx context.Context, req *Null) (*PingerList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPingerList not implemented")
}
func (*UnimplementedPingerServer) GetPingerInfo(ctx context.Context, req *PingerID) (*PingerInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPingerInfo not implemented")
}
func (*UnimplementedPingerServer) GetsStatistics(req *PingerID, srv Pinger_GetsStatisticsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetsStatistics not implemented")
}
func (*UnimplementedPingerServer) GetsIcmpResult(req *PingerID, srv Pinger_GetsIcmpResultServer) error {
	return status.Errorf(codes.Unimplemented, "method GetsIcmpResult not implemented")
}

func RegisterPingerServer(s *grpc.Server, srv PingerServer) {
	s.RegisterService(&_Pinger_serviceDesc, srv)
}

func _Pinger_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uPinger.Pinger/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uPinger.Pinger/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Stop(ctx, req.(*PingerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_GetPingerList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Null)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).GetPingerList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uPinger.Pinger/GetPingerList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).GetPingerList(ctx, req.(*Null))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_GetPingerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).GetPingerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/uPinger.Pinger/GetPingerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).GetPingerInfo(ctx, req.(*PingerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pinger_GetsStatistics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingerID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingerServer).GetsStatistics(m, &pingerGetsStatisticsServer{stream})
}

type Pinger_GetsStatisticsServer interface {
	Send(*Statistics) error
	grpc.ServerStream
}

type pingerGetsStatisticsServer struct {
	grpc.ServerStream
}

func (x *pingerGetsStatisticsServer) Send(m *Statistics) error {
	return x.ServerStream.SendMsg(m)
}

func _Pinger_GetsIcmpResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PingerID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PingerServer).GetsIcmpResult(m, &pingerGetsIcmpResultServer{stream})
}

type Pinger_GetsIcmpResultServer interface {
	Send(*IcmpResult) error
	grpc.ServerStream
}

type pingerGetsIcmpResultServer struct {
	grpc.ServerStream
}

func (x *pingerGetsIcmpResultServer) Send(m *IcmpResult) error {
	return x.ServerStream.SendMsg(m)
}

var _Pinger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "uPinger.Pinger",
	HandlerType: (*PingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _Pinger_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Pinger_Stop_Handler,
		},
		{
			MethodName: "GetPingerList",
			Handler:    _Pinger_GetPingerList_Handler,
		},
		{
			MethodName: "GetPingerInfo",
			Handler:    _Pinger_GetPingerInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetsStatistics",
			Handler:       _Pinger_GetsStatistics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetsIcmpResult",
			Handler:       _Pinger_GetsIcmpResult_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pingGrpc.proto",
}
